server:
  port: 8088
  servlet:
    context-path: /shop-api
spring:
  application:
    name: shop-api
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql 驱动
#    url: jdbc:mysql://121.43.101.104:3306/shop-online?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8 # ?8?
    url: jdbc:mysql://127.0.0.1:3306/shop-online?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8 # ?8?
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配的最大时长(毫秒)，超过这个时长还没可用的连接则发生SQLException,默认30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长(毫秒)，超时则被释放(retired) 默认：10分钟
      pool-name: DateSourceHikariCP   # 连接池名称
      max-lifetime: 1800000           # 连接的生命时长(毫秒)，超时而且没被使用则被释放(retired),默认：30分钟 1800000ms
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  data:
    redis:
      #redis数据库索引(默认为0)
      database: 0
      #redis服务器地址
      host: 127.0.0.1
      #redis服务器连接端口
      port: 6379
      #redis连接密码
      password: root

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.shop.shoponline.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: true # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
